version: '3'
services:
  app:
    build: .
    container_name: my_rails_app
    command: 
      /bin/bash -c 'rm -rf tmp/pids/server.pid; bundle exec rails s -b 0.0.0.0'
    env_file:
      - ./environments/db.env
    environment:
      TZ: "Asia/Tokyo"
      RAILS_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.6.40
    container_name: db_mysql
    restart: always
    ports:
      - 4306:3306
    volumes:
      - db-data:/var/lib/mysql
  web:
    build: 
      context: containers/nginx
    container_name: web_nginx
    ports:
      - '80:80'
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    depends_on:
      - app
volumes:
  db-data:
  public-data:
  tmp-data:
  log-data: