version: '3'
services:
  app:
    build: .
    container_name: my_rails_app
    env_file:
      - ./environments/db.env
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.6.40
    container_name: db_mysql
    env_file:
      - ./environments/db.env
    restart: always
    ports:
      - 4306:3306
    volumes:
      - db-data:/var/lib/mysql
  web:
    build: 
      context: containers/nginx
    container_name: web_nginx
    ports:
      - '80:80'
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    depends_on:
      - app
volumes:
  db-data:
  public-data:
  tmp-data:
  log-data: